# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c33711d19499cdde1525d638b177e308bfc556495a1b6ec6543c862925d62ac70d7a4072905a76fb99b523fde7a32e44743e2e7f09c7f94a2c7b28c7d53c0248

test:
  secret_key_base: b416db6ac8b557d246568977c1832d133f21c5eba55aa67a7b2234c08812fd779a310db65cd7e9575705f6a06ff5b9ea7eeaa48c09b2730414e4c7c257c77890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
